Repository prgrms-web-devcourse/Team_Alchomist_ShakeNMatch_FE, pull requests merged in 2021-12, with the labels that each got.

#5 feat: SM-8 Text Component
  src/components/base/Text/index.tsx
  src/components/base/Text/styled.ts
  src/components/base/Text/types.ts
  src/models/index.ts
  src/stories/base/Text.stories.tsx
  src/utils/constants/size.ts
Labels: 리뷰 요청

#4 feat: SM-6 Button 컴포넌트 및 스토리북 구현
  src/components/base/Button/index.tsx
  src/components/base/Button/styled.ts
  src/components/base/Button/types.ts
  src/models/index.ts
  src/stories/Button.stories.tsx
  src/utils/constants/color.ts
Labels: 리뷰 요청

#17 feat: SM-62 Color 상수화 및 타입 정의
  src/models/types.ts
  src/utils/constants/colors.ts
  tsconfig.path.json
Labels: 리뷰 요청, 미완료

#6 feat: SM-9 Divider Component
  src/components/base/Divider/index.tsx
  src/components/base/Divider/styled.ts
  src/components/base/Divider/types.ts
  src/models/index.ts
  src/models/types.ts
  src/stories/base/Divider.stories.tsx
  src/utils/constants/color.ts
Labels: 리뷰 요청

#14 Feat/sm 41/image
  src/components/base/Image/index.tsx
  src/components/base/Image/styled.ts
  src/components/base/Image/types.ts
  src/stories/Image.stories.tsx
Labels: 리뷰 요청

#7 feat: SM-4 Input Component
  src/App.tsx
  src/components/base/Input/index.tsx
  src/components/base/Input/style.tsx
  src/components/base/Input/types.ts
  src/components/base/Text/styled.ts
  src/components/base/Text/types.ts
  src/models/types.ts
  src/stories/base/Input.stories.tsx
  src/utils/constants/index.ts
  src/utils/constants/mbti.ts
  src/utils/constants/text.ts
  yarn.lock
Labels: 리뷰 요청, 재 리뷰 요청

#26 Feat/sm 65/alias
  .storybook/main.js
  tsconfig.path.json
Labels: 리뷰 요청

#13 feat: SM-10 SectionDivider 컴포넌트 및 스토리 제작
  src/components/base/SectionDivider/index.tsx
  src/components/base/SectionDivider/styled.ts
  src/components/base/SectionDivider/types.ts
  src/stories/base/SectionDivider.stories.tsx
  src/utils/constants/color.ts
Labels: 리뷰 요청

#21 feat: SM-13 Icon 컴포넌트 및 스토리북 구현
  package.json
  src/components/base/Icon/index.tsx
  src/components/base/Icon/styled.ts
  src/components/base/Icon/types.ts
  src/stories/base/Icon.stories.tsx
  src/utils/constants/colors.ts
  src/utils/constants/icon.ts
  yarn.lock
Labels: 리뷰 요청

#12 Feat/SM-14/Modal
  src/components/base/Button/styled.ts
  src/components/base/Button/types.ts
  src/components/base/Modal/index.tsx
  src/components/base/Modal/styled.ts
  src/components/base/Modal/types.ts
  src/hooks/useClickAway.ts
  src/stories/base/Modal.stories.tsx
Labels: 리뷰 요청, 재 리뷰 요청

#20 Feat/sm 52/text button
  src/components/base/Button/styled.ts
  src/components/base/Button/types.ts
  src/components/base/index.ts
  src/components/compound/TextButton/index.tsx
  src/components/compound/TextButton/types.ts
  src/stories/Button.stories.tsx
  src/stories/base/Button.stories.tsx
  src/stories/compound/TextButton.stories.tsx
  src/utils/constants/color.ts
Labels: 리뷰 요청, 재 리뷰 요청

#22 feat: SM-53 ImageButton
  .storybook/main.js
  src/assets/oauthAssets/google_login.png
  src/assets/oauthAssets/kakao_login.png
  src/components/base/Button/styled.ts
  src/components/base/Button/types.ts
  src/components/base/Image/types.ts
  src/components/compound/ImageButton/index.tsx
  src/components/compound/ImageButton/styled.ts
  src/components/compound/ImageButton/types.ts
  src/stories/base/Button.stories.tsx
  src/stories/compound/ImageButton.stories.tsx
  tsconfig.path.json
Labels: 리뷰 요청

#27 Feat/sm 51/uploader - 업로더 컴포넌트 기능 구현 및 스토리북 추가
  src/assets/defaultUploader.svg
  src/components/base/Input/style.tsx
  src/components/base/Input/types.ts
  src/components/base/Uploader/index.tsx
  src/components/base/Uploader/styled.ts
  src/components/base/Uploader/types.ts
  src/stories/base/Uploader.stories.tsx
Labels: 리뷰 요청, 재 리뷰 요청

#29 fix: SM-75 컴포넌트 props type 수정 및 storybook 정리
  src/components/base/Button/types.ts
  src/components/base/Icon/types.ts
  src/components/base/Image/types.ts
  src/components/base/Input/types.ts
  src/components/base/index.ts
  src/components/compound/ImageButton/types.ts
  src/components/compound/TextButton/types.ts
  src/stories/base/Button.stories.tsx
  src/stories/base/Icon.stories.tsx
  src/stories/base/Image.stories.tsx
  src/stories/base/Modal.stories.tsx
  src/stories/base/SectionDivider.stories.tsx
  src/stories/compound/TextButton.stories.tsx
Labels: 리뷰 요청

#25 Feat/sm 55/icon toggle
  src/components/compound/IconToggle/index.tsx
  src/components/compound/IconToggle/styled.ts
  src/components/compound/IconToggle/types.ts
  src/hooks/useToggle.ts
  src/stories/compound/IconToggle.stories.tsx
Labels: 리뷰 요청

#24 Feat/sm 54/text toggle button
  src/components/compound/TextToggle/index.tsx
  src/components/compound/TextToggle/styled.ts
  src/components/compound/TextToggle/types.ts
  src/stories/compound/TextToggleButton.stories.tsx
Labels: 리뷰 요청, 재 리뷰 요청

#23 feat: SM-64 IconButton 및 reset-css 적용, font 적용
  .storybook/preview-head.html
  .storybook/preview.js
  package.json
  public/index.html
  src/components/base/Icon/types.ts
  src/components/compound/IconButton/index.tsx
  src/components/compound/IconButton/styled.ts
  src/components/compound/IconButton/types.ts
  src/index.tsx
  src/stories/compound/IconButton.stories.tsx
  yarn.lock
Labels: 리뷰 요청

#28 feat: SM-69 FormValidateIdentifier
  .storybook/main.js
  src/assets/sounds/shakeSound.mp3
  src/assets/sounds/waterSound.mp3
  src/audio.d.ts
  src/components/domain/FormValidateIdentifier/index.tsx
  src/components/domain/FormValidateIdentifier/styled.ts
  src/components/domain/FormValidateIdentifier/types.ts
  src/stories/domain/FormValidateIdentifier.stories.tsx
  src/utils/constants/colors.ts
Labels: 리뷰 요청

#18 feat: SM-57 Carousel 컴포넌트
  src/assets/carouselTheme/big/color.png
  src/assets/carouselTheme/big/editProfile.png
  src/assets/carouselTheme/big/favorites.png
  src/assets/carouselTheme/big/mbti.png
  src/assets/carouselTheme/big/mood.png
  src/assets/carouselTheme/big/music.png
  src/assets/carouselTheme/big/trending.png
  src/assets/carouselTheme/big/weather.png
  src/assets/carouselTheme/mbti/enfj.svg
  src/assets/carouselTheme/mbti/isfj.svg
  src/assets/carouselTheme/mbti/istj.svg
  src/components/compound/Carousel/CarouselContainer/index.tsx
  src/components/compound/Carousel/CarouselContainer/styled.ts
  src/components/compound/Carousel/CarouselContainer/types.ts
  src/components/compound/Carousel/CarouselItem/index.tsx
  src/components/compound/Carousel/CarouselItem/styled.ts
  src/components/compound/Carousel/CarouselItem/types.ts
  src/components/compound/Carousel/index.ts
  src/hooks/useDebounce.ts
  src/hooks/useThrottle.ts
  src/hooks/useWheel.ts
  src/stories/compound/Carousel.stories.tsx
Labels: 리뷰 요청

#34 Feat: SM-56 Album 컴포넌트
  src/components/compound/Album/index.tsx
  src/components/compound/Album/styled.ts
  src/components/compound/Album/types.ts
  src/stories/compound/Album.stories.tsx
Labels: 리뷰 요청

#15 Feat/sm 50/menu tab
  .eslintrc.js
  src/components/compound/MenuTab/index.tsx
  src/components/compound/MenuTab/styled.ts
  src/components/compound/MenuTab/types.ts
  src/components/compound/index.tsx
  src/stories/compound/MenuTab.stories.tsx
Labels: 리뷰 요청, 재 리뷰 요청

#36 feat: SM-83 TitleSectionContainer 컴포넌트 구현
  src/components/domain/TitleSectionContainer/index.tsx
  src/components/domain/TitleSectionContainer/styled.ts
  src/components/domain/TitleSectionContainer/types.ts
  src/stories/compound/TextButton.stories.tsx
  src/stories/domain/TitleSectionContainer.stories.tsx
Labels: 리뷰 요청

#31 feat: SM-72 Select, UserInput, UserForm 컴포넌트 작성
  src/components/base/Select/index.tsx
  src/components/base/Select/styled.ts
  src/components/base/Select/types.ts
  src/components/base/Text/index.tsx
  src/components/base/Text/styled.ts
  src/components/base/Text/types.ts
  src/components/compound/UserInput/index.tsx
  src/components/compound/UserInput/styled.ts
  src/components/compound/UserInput/types.ts
  src/components/domain/UserForm/index.tsx
  src/components/domain/UserForm/styled.ts
  src/components/domain/UserForm/types.ts
  src/hooks/useForm.ts
  src/models/types.ts
  src/stories/base/Modal.stories.tsx
  src/stories/base/SectionDivider.stories.tsx
  src/stories/base/Select.stories.tsx
  src/stories/domain/UserForm.stories.tsx
  src/utils/constants/index.ts
  src/utils/constants/mbti.ts
  src/utils/constants/user.ts
  src/utils/lib/userValidator.ts
Labels: 리뷰 요청

#32 feat: SM-81 RegisterModal 작성 및 Input, Select 스타일 수정
  src/components/base/Input/style.tsx
  src/components/base/Modal/index.tsx
  src/components/base/Modal/styled.ts
  src/components/base/Modal/types.ts
  src/components/base/Select/styled.ts
  src/components/base/Text/index.tsx
  src/components/compound/UserInput/index.tsx
  src/components/compound/UserInput/styled.ts
  src/components/domain/FormValidateIdentifier/styled.ts
  src/components/domain/RegisterModal/index.tsx
  src/components/domain/RegisterModal/styled.ts
  src/components/domain/RegisterModal/types.ts
  src/components/domain/UserForm/index.tsx
  src/models/types.ts
  src/stories/base/Select.stories.tsx
  src/stories/domain/RegisterModal.stories.tsx
  src/utils/constants/colors.ts
  src/utils/constants/text.ts
Labels: 리뷰 요청

#51 feat: SM-138 Axios instance 및 interceptors 기본 설정
  package.json
  src/utils/apis/config.ts
  src/utils/apis/index.ts
  yarn.lock
Labels: 리뷰 요청

#35 feat: SM-82 ThemeSelector
  src/components/compound/Carousel/CarouselContainer/index.tsx
  src/components/compound/Carousel/CarouselContainer/types.ts
  src/components/domain/ThemeSelector/index.tsx
  src/components/domain/ThemeSelector/styled.ts
  src/components/domain/ThemeSelector/types.ts
  src/models/types.ts
  src/stories/compound/Carousel.stories.tsx
  src/stories/domain/ThemeSelector.stories.tsx
  src/utils/constants/themes.ts
Labels: 리뷰 요청

#41 Feat/sm 84/cocktail list
  src/components/compound/Album/styled.ts
  src/components/domain/CocktailList/index.tsx
  src/components/domain/CocktailList/styled.ts
  src/components/domain/CocktailList/types.ts
  src/stories/domain/CocktailList.stories.tsx
Labels: 리뷰 요청

#40 feat: SM-86 메인페이지 기본 레이아웃 구현
  src/assets/logo/logo_lg.png
  src/assets/logo/logo_md.png
  src/assets/logo/logo_sm.png
  src/components/base/Modal/styled.ts
  src/components/base/Modal/types.ts
  src/components/base/SectionDivider/styled.ts
  src/components/domain/BackButton/index.tsx
  src/components/domain/Logo/index.tsx
  src/components/domain/MainMenuSelector/index.tsx
  src/components/domain/MainMenuSelector/styled.ts
  src/components/domain/MainMenuSelector/types.ts
  src/hooks/useHover.ts
  src/pages/MainPage/index.tsx
  src/pages/MainPage/styled.ts
  src/utils/constants/colors.ts
  src/utils/constants/logos.ts
Labels: 리뷰 요청

#42 feat: SM-92 ThemePage 기능 구현
  craco.config.js
  src/components/base/Text/styled.ts
  src/components/base/Text/types.ts
  src/components/compound/Carousel/CarouselContainer/index.tsx
  src/components/compound/Carousel/CarouselItem/index.tsx
  src/components/compound/Carousel/CarouselItem/styled.ts
  src/components/domain/BackButton/index.tsx
  src/components/domain/BackButton/styled.ts
  src/components/domain/BackButton/types.ts
  src/components/domain/ThemeSelector/index.tsx
  src/pages/ThemePage/index.tsx
  src/pages/ThemePage/styled.ts
  src/stories/domain/IngredientToggleList.stories.tsx
Labels: 리뷰 요청

#37 Feat/SM-71/IngredientCarousel
  src/components/compound/Album/types.ts
  src/components/compound/IconButton/styled.ts
  src/components/domain/IngredientCarousel/index.tsx
  src/components/domain/IngredientCarousel/styled.ts
  src/components/domain/IngredientCarousel/types.ts
  src/stories/domain/IngredientCarousel.stories.tsx
Labels: 리뷰 요청

#45 feat: SM-96 AuthorizationProvider
  src/App.tsx
  src/contexts/Authorization/index.tsx
  src/contexts/Authorization/types.ts
  src/contexts/index.ts
  src/hooks/useSessionStorage.ts
  src/models/types.ts
  src/pages/TestPage/index.tsx
  src/routes/index.tsx
Labels: 리뷰 요청

#47 feat: SM-141 Entity Types 정의
  src/models/types.ts
Labels: 리뷰 요청

#54 feat/SM-97/RatingStar 기능 구현 및 스토리북 추가
  src/components/compound/IconButton/index.tsx
  src/components/domain/RatingStar/index.tsx
  src/components/domain/RatingStar/style.ts
  src/components/domain/RatingStar/types.ts
  src/stories/domain/RatingStar.stories.tsx
Labels: 리뷰 요청

#48 Feat/sm 94/ingredient select modal
  src/components/compound/MenuTab/index.tsx
  src/components/compound/MenuTab/styled.ts
  src/components/compound/MenuTab/types.ts
  src/components/compound/TextToggle/index.tsx
  src/components/compound/TextToggle/types.ts
  src/components/domain/IngredientSelectModal/index.tsx
  src/components/domain/IngredientSelectModal/styled.ts
  src/components/domain/IngredientSelectModal/types.ts
  src/components/domain/IngredientToggleList/index.tsx
  src/components/domain/IngredientToggleList/styled.ts
  src/components/domain/IngredientToggleList/types.ts
  src/components/domain/TitleSectionContainer/index.tsx
  src/components/domain/TitleSectionContainer/types.ts
  src/stories/domain/IngredientSelectModal.stories.tsx
  src/stories/domain/IngredientToggleList.stories.tsx
Labels: 미완료

#53 Feat/sm 144/search page
  src/assets/characters/searchBartender.png
  src/components/domain/CocktailList/index.tsx
  src/components/domain/CocktailList/types.ts
  src/components/domain/SearchCocktailInput/index.tsx
  src/components/domain/SearchCocktailInput/types.ts
  src/components/domain/SectionDividerWithTitle/index.tsx
  src/components/domain/SectionDividerWithTitle/styled.ts
  src/hooks/useDebounce.ts
  src/models/types.ts
  src/pages/SearchPage/index.tsx
  src/pages/SearchPage/styled.ts
  src/stories/domain/CocktailList.stories.tsx
  src/stories/domain/SearchCocktailInput.stories.tsx
Labels: 미완료

#58 Feat/sm 74/cocktail review modal
  src/components/base/Uploader/styled.ts
  src/components/domain/CocktailReviewModal/index.tsx
  src/components/domain/CocktailReviewModal/style.ts
  src/components/domain/CocktailReviewModal/types.ts
  src/components/domain/RatingStar/index.tsx
  src/components/domain/RatingStar/types.ts
  src/stories/domain/CocktailReviewModal.stories.tsx
Labels: 리뷰 요청

#57 fix: SM-147 MainPage, MyPage, ThemePage 연결 및 리팩토링
  src/components/compound/ImageButton/index.tsx
  src/components/domain/CocktailList/styled.ts
  src/components/domain/Header/styled.ts
  src/components/domain/SectionDividerWithTitle/index.tsx
  src/components/domain/SectionDividerWithTitle/types.ts
  src/components/domain/ThemeSelector/index.tsx
  src/components/domain/ThemeSelector/styled.ts
  src/components/domain/TitleSectionContainer/index.tsx
  src/components/domain/TitleSectionContainer/styled.ts
  src/hooks/useDebounce.ts
  src/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/SearchPage/styled.ts
  src/pages/ThemePage/index.tsx
  src/pages/ThemePage/styled.ts
  src/utils/constants/headerHeight.ts
  src/utils/lib/getDomain.ts
Labels: 리뷰 요청

#60 feat: SM-149 LoginPage, RegisterPage 작성 및 Page 연결, 리팩토링
  src/assets/background/background_1.png
  src/components/base/PageContainerWithBackground/index.tsx
  src/components/base/PageContainerWithBackground/styled.ts
  src/components/domain/BackButton/styled.ts
  src/components/domain/KaKaoButton/index.tsx
  src/components/domain/RegisterModal/index.tsx
  src/components/domain/RegisterModal/styled.ts
  src/components/domain/SectionDividerWithTitle/index.tsx
  src/components/domain/SectionDividerWithTitle/types.ts
  src/contexts/Authorization/index.tsx
  src/contexts/Authorization/types.ts
  src/pages/LoginPage/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/MainPage/styled.ts
  src/pages/MyPage/index.tsx
  src/pages/RegisterPage/index.tsx
  src/pages/TestPage/index.tsx
  src/routes/index.tsx
  src/utils/constants/colors.ts
Labels: 리뷰 요청

#44 feat: SM-90 ShoppingItem
  src/components/domain/ShoppingItem/index.tsx
  src/components/domain/ShoppingItem/styled.ts
  src/components/domain/ShoppingItem/types.ts
  src/stories/domain/ShoppingItem.stories.tsx
  src/utils/constants/colors.ts
Labels: 리뷰 요청

#61 feat: SM-152 headerToolTip
  src/components/base/Tooltip/styled.ts
  src/components/domain/Header/index.tsx
  src/components/domain/Header/styled.ts
Labels: 리뷰 요청

#66 Feat/sm 153/cocktail detail modal
  src/components/base/Modal/styled.ts
  src/components/compound/Album/index.tsx
  src/components/compound/Album/types.ts
  src/components/compound/MenuTab/index.tsx
  src/components/domain/CocktailDetailModal/IngredientItem/index.tsx
  src/components/domain/CocktailDetailModal/IngredientItem/style.ts
  src/components/domain/CocktailDetailModal/IngredientItem/types.ts
  src/components/domain/CocktailDetailModal/UserReviewItem/index.tsx
  src/components/domain/CocktailDetailModal/UserReviewItem/style.ts
  src/components/domain/CocktailDetailModal/UserReviewItem/types.ts
  src/components/domain/CocktailDetailModal/index.tsx
  src/components/domain/CocktailDetailModal/style.ts
  src/components/domain/CocktailDetailModal/types.ts
  src/components/domain/CocktailReviewModal/index.tsx
  src/components/domain/TitleSectionContainer/styled.ts
  src/stories/compound/Carousel.stories.tsx
  src/stories/domain/CocktailDetailModa.stories.tsx
  src/stories/domain/CocktailReviewModal.stories.tsx
Labels: 리뷰 요청

#71 feat: SM-163 Loader Component 구현
  src/assets/loader/shaker.png
  src/components/compound/Loader/index.tsx
  src/components/compound/Loader/styled.ts
  src/stories/compound/Loader.stories.tsx
Labels: 리뷰 요청

#74 refactor: SM-167 modal animation
  src/components/base/Modal/styled.ts
Labels: 리뷰 요청

#72 refactor: SM-165 Theme Selector 아이콘들 적용
  src/assets/carouselTheme/big/index.ts
  src/assets/carouselTheme/colorIcons/index.ts
  src/assets/carouselTheme/index.ts
  src/assets/carouselTheme/mbtiIcons/index.ts
  src/assets/carouselTheme/moodIcons/index.ts
  src/assets/carouselTheme/musicIcons/index.ts
  src/assets/carouselTheme/weatherIcons/index.ts
  src/components/base/Image/index.tsx
  src/components/compound/Carousel/CarouselItem/index.tsx
  src/components/domain/ThemeSelector/index.tsx
  src/utils/constants/themes.ts
Labels: 리뷰 요청

#76 Feat/sm 159/ingredient item
  src/components/compound/Album/types.ts
  src/components/domain/CocktailDetailModal/IngredientItem/index.tsx
  src/components/domain/CocktailDetailModal/IngredientItem/style.ts
  src/components/domain/CocktailDetailModal/IngredientItem/types.ts
  src/components/domain/CocktailDetailModal/UserReviewItem/index.tsx
  src/components/domain/CocktailDetailModal/UserReviewItem/types.ts
  src/components/domain/CocktailDetailModal/index.tsx
  src/components/domain/CocktailDetailModal/types.ts
  src/stories/domain/CocktailDetailModal.stories.tsx
Labels: 리뷰 요청

#77 Feat/sm 168/toggle list icon
  .env
  src/assets/cocktails/index.ts
  src/assets/ingredients/index.ts
  src/components/domain/CocktailList/index.tsx
  src/components/domain/CocktailList/types.ts
  src/components/domain/IngredientCarousel/index.tsx
  src/components/domain/IngredientCarousel/types.ts
  src/pages/JangoPage/index.tsx
Labels: 리뷰 요청

#67 Feat/sm 154/search bot
  src/assets/characters/searchBot.png
  src/components/domain/ChangingSpeech/index.tsx
  src/components/domain/ChangingSpeech/styled.ts
  src/components/domain/ChangingSpeech/types.ts
  src/components/domain/SearchBot/index.tsx
  src/components/domain/SearchBot/styled.ts
  src/components/domain/SearchBot/types.ts
  src/pages/ErrorPage/index.tsx
  src/pages/JangoPage/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/ThemePage/index.tsx
  src/stories/compound/SearchBot.stories.tsx
  src/stories/domain/ChangingSpeech.stories.tsx
  src/utils/constants/bartender.ts
Labels: 리뷰 요청

#70 feat: SM-162 KaKao OAuth 로그인
  src/contexts/Authorization/index.tsx
  src/contexts/Authorization/types.ts
  src/hooks/useAxios.ts
  src/models/types.ts
  src/pages/OAuthKaKaoPage/index.tsx
  src/pages/OAuthKaKaoPage/styled.ts
  src/pages/RegisterPage/index.tsx
Labels: 리뷰 요청

#84 refactor: SM-170 스타일 수정
  src/components/domain/CocktailList/styled.ts
  src/components/domain/Header/styled.ts
  src/index.tsx
  src/pages/SearchPage/index.tsx
Labels: 리뷰 요청

#88 Feat/sm 178/api to cocktail detail modal
  src/components/compound/Album/index.tsx
  src/components/compound/Album/types.ts
  src/components/compound/MenuTab/index.tsx
  src/components/domain/CocktailDetailModal/IngredientItem/index.tsx
  src/components/domain/CocktailDetailModal/IngredientItem/types.ts
  src/components/domain/CocktailDetailModal/UserReviewItem/index.tsx
  src/components/domain/CocktailDetailModal/UserReviewItem/types.ts
  src/components/domain/CocktailDetailModal/index.tsx
  src/components/domain/CocktailDetailModal/types.ts
  src/components/domain/CocktailList/types.ts
  src/components/domain/CocktailReviewModal/index.tsx
  src/components/domain/CocktailReviewModal/types.ts
  src/hooks/useDebounce.ts
  src/models/types.ts
  src/pages/SearchPage/index.tsx
  src/stories/domain/CocktailReviewModal.stories.tsx
Labels: 리뷰 요청

#89 feat: SM-184 Album에클릭 이벤트 핸들러 함수 바인딩
  src/components/domain/CocktailDetailModal/index.tsx
  src/components/domain/CocktailList/index.tsx
Labels: 리뷰 요청

#90 Feat/sm 186/ingredient item
  src/components/domain/CocktailDetailModal/IngredientItem/index.tsx
  src/components/domain/CocktailDetailModal/IngredientItem/style.ts
  src/components/domain/CocktailDetailModal/IngredientItem/types.ts
Labels: 리뷰 요청

#91 Feat/sm 179/jango page api
  src/components/domain/IngredientCarousel/types.ts
  src/components/domain/IngredientSelectModal/index.tsx
  src/components/domain/index.ts
  src/contexts/Jango/index.tsx
  src/contexts/Jango/types.ts
  src/pages/JangoPage/index.tsx
  src/pages/JangoPage/styled.ts
  src/stories/domain/IngredientCarousel.stories.tsx
Labels: 리뷰 요청

#97 feat: SM-191 EditProfile API 로직 작성
  src/models/types.ts
  src/pages/MyPage/index.tsx
  src/pages/MyPage/reducer.ts
Labels: 리뷰 요청

#95 Feat/sm 189/review item
  src/components/domain/CocktailDetailModal/UserReviewItem/index.tsx
  src/components/domain/CocktailDetailModal/UserReviewItem/style.ts
  src/components/domain/CocktailDetailModal/UserReviewItem/types.ts
  src/components/domain/CocktailDetailModal/types.ts
  src/stories/domain/UserReviewItem.stories.tsx
Labels: 리뷰 요청

#98 feat: SM-192 유저 즐겨찾기목록 api 로직 작성
  src/pages/MyPage/index.tsx
  src/pages/MyPage/reducer.ts
  src/pages/MyPage/types.ts
Labels: 리뷰 요청

#100 refactor: SM-185 MainPage 스타일 수정
  src/components/base/Text/styled.ts
  src/components/domain/MainMenuSelector/styled.ts
  src/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/MainPage/styled.ts
Labels: 리뷰 요청

#108 Feat/sm 201/review post api
  src/components/domain/CocktailDetailModal/UserReviewItem/index.tsx
  src/components/domain/CocktailReviewModal/index.tsx
  src/models/types.ts
Labels: 리뷰 요청

#111 Feat/sm 203/optimistic updates
  src/components/domain/CocktailDetailModal/UserReviewItem/index.tsx
  src/components/domain/CocktailDetailModal/UserReviewItem/types.ts
  src/components/domain/CocktailDetailModal/index.tsx
  src/components/domain/CocktailReviewModal/index.tsx
  src/components/domain/CocktailReviewModal/types.ts
  src/models/types.ts
  src/stories/domain/CocktailReviewModal.stories.tsx
Labels: 리뷰 요청

#116 refactor: SM-205 불필요한 JangoContext 기능 삭제
  src/components/domain/CocktailDetailModal/index.tsx
  src/components/domain/IngredientSelectModal/index.tsx
  src/components/domain/IngredientSelectModal/types.ts
  src/contexts/Authorization/index.tsx
  src/contexts/Jango/index.tsx
  src/contexts/Jango/types.ts
  src/pages/JangoPage/index.tsx
  src/routes/JangoRoutes/index.tsx
  src/stories/domain/IngredientSelectModal.stories.tsx
Labels: 리뷰 요청

#117 fix: SM-208 CocktailList 머지 conflict 병합 오류 수정
  src/components/domain/CocktailDetailModal/index.tsx
  src/components/domain/CocktailDetailModal/types.ts
  src/components/domain/CocktailList/index.tsx
Labels: 리뷰 요청

#121 release: v0.2.0
  .eslintrc.js
  README.md
  api/naverShop.ts
  package.json
  src/components/domain/CocktailDetailModal/IngredientItem/index.tsx
  src/components/domain/KaKaoButton/index.tsx
  src/pages/ShoppingPage/index.tsx
  tsconfig.json
  yarn.lock
Labels: 배포

#125 fix: SM-213 register 페이지에서 최초 initialValidate 제거
  src/components/domain/UserForm/index.tsx
Labels: 리뷰 요청

#124 fix: SM-212 bookmark null bug 수정
  src/components/domain/CocktailDetailModal/index.tsx
  src/contexts/Authorization/index.tsx
Labels: 리뷰 요청

#126 release: v1.0.1
  src/components/domain/CocktailDetailModal/index.tsx
  src/components/domain/UserForm/index.tsx
  src/contexts/Authorization/index.tsx
Labels: 배포

#128 release: v1.0.2
  src/assets/defaultUploader.svg
  src/components/base/index.ts
  src/components/compound/Uploader/index.tsx
  src/components/compound/Uploader/styled.ts
  src/components/compound/Uploader/types.ts
  src/components/compound/index.tsx
  src/components/domain/CocktailDetailModal/index.tsx
  src/components/domain/CocktailReviewModal/index.tsx
  src/components/domain/CocktailReviewModal/style.ts
  src/stories/compound/Uploader.stories.tsx
Labels: 배포
